### ISSUE TITLE
v2.0.1 Release Checklist

### ISSUE THREAD

**Issue by cipherboy** [openbao/openbao#501]
## Pre-release checklist

 - [x] Designate a release manager and assign them this issue. @JanMa
 - [x] Clone this template into a GitHub release issue.
 - [x] Identify target release version (major, minor, or patch) and milestones
       (alpha, beta, ...). -- `v2.0.1`, patch update to GA `v2.0.0`
 - [x] Identify and communicate the release timeline.
      - [x] Community meeting -- announced August 15th as ad-hoc release pending maintainer availability 
      - [x] ~OpenBao Core Mailing list~
      - [x] ~TSC Mailing List~
      - [x] ~Matrix~
      - [x] GitHub milestones: https://github.com/openbao/openbao/milestone/5 
 - [x] Ensure relevant features and bug fixes are present in the release. --> https://github.com/openbao/openbao/tree/release/2.0.x 
 - [x] Check generated changelog via `make release-changelog` and make any
       necessary updates to entries.
 - [x] Draft release notification announcement.
 - [x] ~Tag new API versions (including in auth plugins), if necessary.~
      - [x] ~When bumping API major version, ensure `api/go.mod` is updated to
            the new version.~
 - [x] ~Update SDK to use the new API version, if necessary.~
      - [x] ~When bumping SDK major version, ensure `sdk/go.mod` is updated to
            the new version.~
 - [x] ~Tag new SDK version, if necessary.~
 - [x] ~Update first-party external dependencies to use new API & SDK
       modules, if necessary.~
      - [x] ~[`go-kms-wrapping`](https://github.com/openbao/go-kms-wrapping)~
      - [x] ~[`go-secure-stdlib`](https://github.com/openbao/go-secure-stdlib)~
      - [x] ~[`openbao-template`](https://github.com/openbao/openbao-template)~
 - [x] ~Update API, SDK, and first-party external dependencies in main
       `go.mod`. While API and SDK always use the built-in version, the
       first-party external modules still use the external version and thus
       must be updated.~
 - [x] Update external dependencies with vulnerabilities. Major changes should
       be done earlier in the release cycle to give the community time to find
       any breaking issues. -- #505.
 - [x] ~Update container image base layer versions.~ Already latest Alpine, RHEL versions.
 - [x] Update Go version pinning in testing; ~go-releaser always uses the
       latest toolchain version~. Fixed in #504.

## Release checklist

 - [x] Open PR to update `CHANGELOG.md` and release notes on website.
 - [x] Tag release commit (`CHANGELOG.md` change).
 - [x] Start [release workflow](https://github.com/openbao/openbao/actions/workflows/release.yml):
       select target tag, and set applicable pre-release/latest set
       (pre-releases should not be marked latest on GitHub).
 - [x] Manually upload GPG signing key to release artifacts.
 - [x] Spot-check release artifacts:
      - [x] Container images work.
      - [x] Linux binaries work.
      - [x] Website download page.
      - [x] CoSign and GPG Signatures on binaries.
 - [x] ~In the event of issues during the release that require new tags to be
       pushed, write a postmortem indicating why.~
 - [x] Share release notification announcement:
      - [x] OpenBao Core mailing list (cc TSC mailing list)
      - [x] GitHub Discussions
      - [x] Link from Matrix
      - [x] Mention in next community meeting & TSC meetings.
 - [x] Close the release milestone on GitHub.
 - [x] ~For large releases, work with LF Edge for a release blog post.~
