### ISSUE TITLE
v2.0.2 Release Checklist

### ISSUE THREAD

**Issue by JanMa** [openbao/openbao#587]
# Release checklist

This checklist was created after the v2.0.0 release in order to facilitate
a better release process going forward.

## Pre-release checklist

 - [x] Designate a release manager and assign them this issue.
 - [x] Clone this template into a GitHub release issue.
 - [x] Identify target release version (major, minor, or patch) and milestones
       (alpha, beta, ...).
 - [x] Identify and communicate the release timeline.
      - [x] Community meeting
      - [ ] OpenBao Core Mailing list
      - [ ] TSC Mailing List
      - [ ] Matrix
      - [x] GitHub milestones
 - [x] Ensure relevant features and bug fixes are present in the release.
 - [x] Check generated changelog via `make release-changelog` and make any
       necessary updates to entries.
 - [x] Draft release notification announcement.

## Release checklist

 - [x] Open PR to update `CHANGELOG.md` and release notes on website.
 - [x] Tag release commit (`CHANGELOG.md` change).
 - [x] Start [release workflow](https://github.com/openbao/openbao/actions/workflows/release.yml):
       select target tag, and set applicable pre-release/latest set
       (pre-releases should not be marked latest on GitHub).
 - [x] Manually upload [GPG signing key](https://openbao.org/assets/openbao-gpg-pub-20240618.asc)
       to the release artifacts.
 - [x] Spot-check release artifacts:
      - [x] Container images work.
      - [x] Linux binaries work.
      - [x] Website download page.
      - [x] CoSign and GPG Signatures on binaries.
 - [ ] In the event of issues during the release that require new tags to be
       pushed, write a postmortem indicating why.
 - [x] Share release notification announcement:
      - [x] OpenBao Core mailing list (cc TSC mailing list)
      - [x] GitHub Discussions
      - [x] Link from Matrix
      - [ ] Mention in next community meeting & TSC meetings.
 - [x] Close the release milestone on GitHub.

**Comment by JanMa** [comment]
Release announcement:

```
Greetings, OpenBao community!

On behalf of the OpenBao TSC and Development Working Group, I'm happy to announce the 2.0.2 patch release is available now!

Release binaries are available on GitHub: https://github.com/openbao/openbao/releases/tag/v2.0.2
Signing is performed using GPG or cosign and rekor.

Container images have been pushed to the following registries:

 - quay: https://quay.io/repository/openbao/openbao?tab=tags&tag=latest and https://quay.io/repository/openbao/openbao-ubi?tab=tags&tag=latest
 - ghcr: https://github.com/openbao/openbao/pkgs/container/openbao and https://github.com/openbao/openbao/pkgs/container/openbao-ubi
 - dockerhub: https://hub.docker.com/r/openbao/openbao and https://hub.docker.com/r/openbao/openbao-ubi; note that this has lower rate limits until our account is approved as an OSS community.

For a full list of changes over v2.0.1, check out the release tag on GitHub: https://github.com/openbao/openbao/releases/tag/v2.0.2

This release has seen a few stabilizations over v2.0.1:

 - Further improved support for Kubernetes
 - Fixed CVE-2024-7594 in the SSH secret engine


Many thanks to the community for making this release possible and all the contributions!


Happy testing!

Jan M. on behalf of the OpenBao Development WG:
Dan G.
Alex S.
Nathan P.

---

To verify Cosign signed artifacts, use `rekor-cli` or `curl` to pull the entry from Rekor: https://edu.chainguard.dev/open-source/sigstore/rekor/how-to-verify-file-signatures-with-rekor-or-curl/

For example, to verify `checksums.txt` with the `checksums.txt.sig` stored locally:

$ SHASUM="$(openssl sha256 -r checksums.txt | awk '{print $1}')"
bc53476e7e69c98650bf69690caf1aa32dc08c19735375819ae3b29bb9c2b733
$ curl -X POST -H "Content-type: application/json" 'https://rekor.sigstore.dev/api/v1/index/retrieve' --data-raw "{\"hash\":\"sha256:$SHASUM\"}"
24296fb24b8ad77aedcc1a0cea8b33a04926d6f3b8db35107a1e864c007bb4aa84416a5153cc0bca
$ UUID=24296fb24b8ad77aedcc1a0cea8b33a04926d6f3b8db35107a1e864c007bb4aa84416a5153cc0bca
$ curl -X GET "https://rekor.sigstore.dev/api/v1/log/entries/${UUID}" > response.json
$ jq -r ".[\"$UUID\"].body" < response.json | base64 -d | jq -r '.spec.signature.publicKey.content' | base64 -d > certificate.pem
$ base64 -d < checksums-linux.txt.sig > checksums-linux.txt.rawsig
$ openssl pkeyutl -verify -certin -inkey certificate.pem -sigfile checksums-linux.txt.rawsig -in checksums-linux.txt -rawin
Signature Verified Successfully

To verify GPG signed artifacts, use `gpg2` from the command line. For example, to verify `checksums-freebsd.txt` with the `checksums-freebsd.txt.gpgsig` stored locally:

$ gpg2 --verify checksums-freebsd.txt.gpgsig checksums-freebsd.txt
gpg: Signature made Wed 17 Jul 2024 06:12:03 PM EDT
gpg:                using RSA key E617DCD4065C2AFC0B2CF7A7BA8BC08C0F691F94
gpg: Good signature from "OpenBao <openbao@lists.lfedge.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 66D1 5FDD 8728 7219 C8E1  5478 D200 CD70 2853 E6D0
     Subkey fingerprint: E617 DCD4 065C 2AFC 0B2C  F7A7 BA8B C08C 0F69 1F94

Please make sure you have the OpenBao GPG key in your keyring:

$ gpg2 --import openbao-gpg-pub-20240618.asc
gpg: key D200CD702853E6D0: public key "OpenBao <openbao@lists.lfedge.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1

This key is published on our release and will be published on the website. 
```
