### ISSUE TITLE
Broader usage of Transactions

### ISSUE THREAD

**Issue by cipherboy** [openbao/openbao#607]
**Is your feature request related to a problem? Please describe.**

In #296, #292, #498, and #560 , initial support for transactions were added to the underlying storage backend and to the PKI and K/V secrets engines. However, there's many more places this can be used. 

**Describe the solution you'd like**

Secrets: 

- [ ] More PKI operations use transactions
- [ ] Transit is evaluated for transaction usage
- [ ] SSH is evaluated for transaction usage
- [ ] Database is evaluated for transaction usage
- [ ] RabbitMQ is evaluated for transaction usage
- [ ] totp is evaluated for transaction usage
- [ ] OpenLDAP is evaluated for transaction usage
- [ ] KVv1 is evaluated for transaction usage

Auth:

- [ ] AppRole is evaluated for transaction usage
- [ ] Cert is evaluated for transaction usage
- [ ] JWT is evaluated for transaction usage
- [ ] Kerberos is evaluated for transaction usage
- [ ] Kubernetes is evaluated for transaction usage
- [ ] LDAP is evaluated for transaction usage
- [ ] Radius is evaluated for transaction usage
- [ ] Token is evaluated for transaction usage
- [ ] Userpass is evaluated for transaction usage

Core:

- [ ] Token store
- [ ] Policy store
- [ ] ... more?

**Describe alternatives you've considered**

Some places such as identity, mfa, and others may rely on MemDB and thus don't immediately need transactions. 

**Explain any additional use-cases**

n/a

**Additional context**

**Comment by v0nNemizez** [comment]
I can help with some of these :)

**Comment by cipherboy** [comment]
@v0nNemizez Cool! Let me know if you have any questions. I'd suggest tackling each in separate issues so we get proper changelog entries for them all. :-)

**Comment by suprjinx** [comment]
It seems like there'd be a way to open/commit/rollback Transactions in a global way -- eg, via middleware applied to all endpoints.

**Comment by suprjinx** [comment]
> 
> All this to say, I think these transactions are a little different than most are used to, so we might want to handle them individually or have an escape hatch.

Could we check for the existence of a transaction (perhaps in Context) and use it automatically unless we decided to explicitly forego? So, eg, PKI CRL could open a new transaction-less connection for reading entries, but will otherwise read/write with the active transaction where available?

**Comment by cipherboy** [comment]
@suprjinx I think we'd reverse it (put the transaction in the `req.Storage` and put the parent context in the context). Then handlers are still transactionable by default.

Ah, but another wrench in that: read HTTP handlers can perform storage writes and write operations need not. So we'd proactively be acquiring a write transaction, which may behave differently than acquiring a read transaction. I think what this means is that we'd probably want to annotate each handler with a "read-only transaction" boolean, which defaults to false, but can be set to true if desired. This would require extending the path handler definitions in `sdk/framework`'s `OperationHandler` function, probably `OperationProperties`...

If you want to go for it, I'd be in favor of it, but we'll want to test with some third-party plugins to make sure all behaves as expected.

**Comment by suprjinx** [comment]
Well since there's an established pattern, I'll just follow what was done for KV and PKI -- I'll start with Auth JWT since i've been working in that package already (presumably anything that writes to Storage).

**Comment by cipherboy** [comment]
@suprjinx If you've not gotten too far, I've changed my mind slightly. Mind holding on the core updates until Namespaces are ready? I think we'll be modifying many such areas and that'll make the eventual feature merge hard.

**Comment by cipherboy** [comment]
With the change in #1102, many places where listing is performed should now be both paginated and transactional.

**Comment by suprjinx** [comment]
I am looking now at `core/expiration manager`
