### ISSUE TITLE
Release Checklist - v2.1.0-beta20241114

### ISSUE THREAD

**Issue by cipherboy** [openbao/openbao#700]
## Pre-release checklist

 - [x] Designate a release manager and assign them this issue. @cipherboy 
 - [x] Clone this template into a GitHub release issue.
 - [x] Identify target release version (major, minor, or patch) and milestones
        (alpha, beta, ...). -- `v2.1.0-beta20241114`
 - [x] Identify and communicate the release timeline.
      - [x] ~Community meeting~
      - [x] ~OpenBao Core Mailing list~
      - [x] ~TSC Mailing List~
      - [x] Matrix
      - [x] GitHub milestones
 - [x] Ensure relevant features and bug fixes are present in the release.
 - [x] Check generated changelog via `make release-changelog` and make any
       necessary updates to entries.
 - [x] Draft release notification announcement.
 - [x] Tag new API versions (including in auth plugins), if necessary.
      - [x] When bumping API major version, ensure `api/go.mod` is updated to
            the new version.
 - [x] Update SDK to use the new API version, if necessary. -- #705
      - [x] When bumping SDK major version, ensure `sdk/go.mod` is updated to
            the new version.
 - [x] Tag new SDK version, if necessary.
 - [x] Update first-party external dependencies to use new API & SDK
       modules, if necessary.
      - [x] [`go-kms-wrapping`](https://github.com/openbao/go-kms-wrapping) -- deemed unnecessary per https://github.com/openbao/openbao/issues/700#issuecomment-2474833011
      - [x] ~[`go-secure-stdlib`](https://github.com/openbao/go-secure-stdlib)~ -- no updates
      - [x] ~[`openbao-template`](https://github.com/openbao/openbao-template)~ -- no updates
 - [x] Update API, SDK, and first-party external dependencies in main
       `go.mod`. While API and SDK always use the built-in version, the
       first-party external modules still use the external version and thus
       must be updated. - #706 needs to be done before #705. #708 handles SDK update.
 - [x] Update external dependencies with vulnerabilities. Major changes should
       be done earlier in the release cycle to give the community time to find
       any breaking issues.
 - [x] Update container image base layer versions. - #701
 - [x] Update Go version pinning in `/.go-release` and in the the `toolchain`
       directive in `go.mod`; go-releaser uses this version via a custom
       (in-repo) `set-up-go` action. - #699 

## Release checklist

 - [x] Open PR to update `CHANGELOG.md` and release notes on website. -- #707 
 - [x] Tag release commit (`CHANGELOG.md` change).
 - [x] Start [release workflow](https://github.com/openbao/openbao/actions/workflows/release.yml):
       select target tag, and set applicable pre-release/latest set
       (pre-releases should not be marked latest on GitHub). --> ~https://github.com/openbao/openbao/actions/runs/11836578853 failed due to goreleaser updates~ ~https://github.com/openbao/openbao/actions/runs/11836811742 failed due to Docker & Solaris/Illumos support~ ~https://github.com/openbao/openbao/actions/runs/11838380273 failed due to RISC-V support missing from new bbolt dep due to raft-bboltdb upgrade~. https://github.com/openbao/openbao/actions/runs/11840606774
 - [x] Manually upload [GPG signing key](https://openbao.org/assets/openbao-gpg-pub-20240618.asc)
       to the release artifacts.
 - [x] Spot-check release artifacts:
      - [x] Container images work.
      - [x] Linux binaries work.
      - [x] Website download page.
      - [x] CoSign and GPG Signatures on binaries.
 - [x] In the event of issues during the release that require new tags to be
       pushed, write a postmortem indicating why.
      - [In our release workflow](https://github.com/openbao/openbao/blob/main/.github/workflows/release.yml#L136), we pin to the latest goreleaser version, which means our config version needs to be validated first. This will be added to the release checklist. 
      - In a [recent pull request](https://github.com/openbao/openbao/pull/505), we had unknowingly broken Illumos and Solaris support. This highlights the need for adequate CI for all platforms we release on. Potentially downstream distros and package managers would be a good place for obscure hardware combinations or other internal packages.
 - [x] Share release notification announcement:
      - [x] OpenBao Core mailing list (cc TSC mailing list)
      - [x] GitHub Discussions
      - [x] Link from Matrix
      - [x] Mention in next community meeting & TSC meetings.
 - [x] Close the release milestone on GitHub.
 - [x] ~For large releases, work with LF Edge for a release blog post.~

**Comment by cipherboy** [comment]
@JanMa @DanGhita I will tag a new API and SDK module and pull in the latest `go-kms-wrapping` changes, but I will not update `go-kms-wrapping` to use the new API/SDK; the only change that I think impacts us is the removal of `go-rootcerts`, which I don't think warrants updating `go-kms-wrapping`. 

Objections?

**Comment by cipherboy** [comment]
@JanMa Based on the following:


<details>

<summary> go-kms-wrapping changed files since last tag </summary>

```
$ git diff --name-only v2.1.0...HEAD
.github/workflows/go.yml
Makefile
README.md
extras/crypto/derived_reader.go
extras/crypto/derived_reader_test.go
extras/crypto/hmac_sha256.go
extras/crypto/hmac_sha256_test.go
extras/crypto/isnil.go
extras/crypto/options.go
extras/crypto/sha256sum.go
extras/crypto/sha256sum_test.go
extras/crypto/testing.go
extras/kms/.gitignore
extras/kms/CHANGELOG.md
extras/kms/Makefile
extras/kms/README.md
extras/kms/data_key.go
extras/kms/data_key_test.go
extras/kms/data_key_version.go
extras/kms/data_key_version_test.go
extras/kms/docker-compose.yml
extras/kms/docs.go
extras/kms/errors.go
extras/kms/examples/Dockerfile
extras/kms/examples/README.md
extras/kms/examples/cli/.gitignore
extras/kms/examples/cli/README.md
extras/kms/examples/cli/main.go
extras/kms/examples/config.go
extras/kms/examples/db.go
extras/kms/examples/docker-compose.yml
extras/kms/examples/fs.go
extras/kms/examples/go.mod
extras/kms/examples/go.sum
extras/kms/examples/oidc.go
extras/kms/examples/run.sh
extras/kms/examples/scope.go
extras/kms/examples/sqlite-migrations/10_scopes.up.sql
extras/kms/examples/sqlite-migrations/15_oidc.up.sql
extras/kms/go.mod
extras/kms/go.sum
extras/kms/id.go
extras/kms/id_test.go
extras/kms/key.go
extras/kms/key_purpose.go
extras/kms/kms.go
extras/kms/kms_internal_test.go
extras/kms/kms_test.go
extras/kms/migrations/fs.go
extras/kms/migrations/postgres/01_domain_types.up.sql
extras/kms/migrations/postgres/02_version.up.sql
extras/kms/migrations/postgres/03_keys.up.sql
extras/kms/migrations/postgres/04_keys.up.sql
extras/kms/migrations/postgres/05_key_rewrap.up.sql
extras/kms/migrations/postgres/06_kms_collection_version.up.sql
extras/kms/migrations/postgres/07_mutable_root_key_version.up.sql
extras/kms/migrations/sqlite/02_version.up.sql
extras/kms/migrations/sqlite/04_keys.up.sql
extras/kms/migrations/sqlite/05_key_rewrap.up.sql
extras/kms/migrations/sqlite/06_kms_collection_version.up.sql
extras/kms/migrations/sqlite/07_mutable_root_key_version.up.sql
extras/kms/option.go
extras/kms/option_test.go
extras/kms/query.go
extras/kms/repository.go
extras/kms/repository_data_key.go
extras/kms/repository_data_key_test.go
extras/kms/repository_data_key_version.go
extras/kms/repository_data_key_version_test.go
extras/kms/repository_root_key.go
extras/kms/repository_root_key_test.go
extras/kms/repository_root_key_version.go
extras/kms/repository_root_key_version_test.go
extras/kms/repository_test.go
extras/kms/root_key.go
extras/kms/root_key_test.go
extras/kms/root_key_version.go
extras/kms/root_key_version_test.go
extras/kms/schema.go
extras/kms/schema_test.go
extras/kms/testing.go
extras/kms/testing_test.go
extras/kms/tools/tools.go
extras/structwrapping/README.md
extras/structwrapping/structwrapping.go
extras/structwrapping/structwrapping_test.go
go.mod
go.sum
wrappers/awskms/go.mod
wrappers/awskms/go.sum
wrappers/transit/go.mod
wrappers/transit/go.sum
wrappers/transit/transit_client.go
wrappers/transit/transit_test.go
```

</details>

The following tags need to occur:

```
v2.2.0
wrappers/awskms/v2.2.0
wrappers/transit/v2.2.0
```

as the changes to `extras/` were all removals.

Note that g-k-w tags are intentionally out-of-sync from openbao. Thoughts?

**Comment by cipherboy** [comment]
Release branch has been created: https://github.com/openbao/openbao/tree/release/2.1.x
