### ISSUE TITLE
Tracking: Reintroduction of UI to Release Builds

### ISSUE THREAD

**Issue by cipherboy** [openbao/openbao#739]
This issue tracks the work necessary to reintroduce the UI to release builds:

- [x] #74, to remove references to HashiCorp assets
    - [x] #643 to remove Vault references on sign-in page
    - [x] #668 to remove Vault references on sidebar, &c
    - [x] #669 to remove references to HashiCorp documentation
    - [x] #683 to fix more documentation links & tests
    - [x] #788 to remove the Vault logo in MFA & OIDC graphics
- [x] #129, to remove references to Vault Enterprise features
    - [x] #684, to remove the license banner
    - [x] #734, to remove the client counts mirroring #194
    - [x] #735 to remove HCP Link status
    - [x] #737, to remove Sentinel Policies from
    - [x] #738, to remove PR/DR replication references
- [x] #154, to fix the main test suite
    - [x] #784, to start fixing several test failures
- [ ] #731, to build with modern versions of NodeJS
- [x] #752, to address outdated dependencies in the UI.
   - [x] #807 addresses this in the current release but will need to be redone before release.
- [ ] (unscoped) to add a shared pipeline stage to build the UI and add it to release artifacts

Optionally:

- [ ] #417, to fix UI builds on Windows

**Comment by arminfelder** [comment]
@cipherboy I fixed a few issues, but there are still around 20 failing 

https://github.com/openbao/openbao/pull/784

**Comment by cipherboy** [comment]
@arminfelder Thank you! I'll try to take a look at the remaining ones shortly :-)
