### ISSUE TITLE
OpenBao v2.1.0 - Release Checklist

### ISSUE THREAD

**Issue by cipherboy** [openbao/openbao#768]
## Pre-release checklist

 - [x] Designate a release manager and assign them this issue. --> @cipherboy 
 - [x] Clone this template into a GitHub release issue.
 - [x] Identify target release version (major, minor, or patch) and milestones
        (alpha, beta, ...). --> v2.1.0 (GA)
 - [x] Identify and communicate the release timeline.
      - [x] Community meeting
      - [x] OpenBao Core Mailing list
      - [x] TSC Mailing List
      - [x] Matrix
      - [x] GitHub milestones
 - [x] Ensure relevant features and bug fixes are present in the release. --> nothing new over v2.1.0-beta.3
 - [x] Check generated changelog via `make release-changelog` and make any
        necessary updates to entries. --> nothing new over v2.1.0-beta.3
 - [x] Draft release notification announcement.
 - [x] ~Tag new API versions (including in auth plugins), if necessary.~ No material changes over beta.
      - [x] ~When bumping API major version, ensure `api/go.mod` is updated to
              the new version.~
 - [x] ~Update SDK to use the new API version, if necessary.~ No material changes over beta.
      - [x] ~When bumping SDK major version, ensure `sdk/go.mod` is updated to
            the new version.~
 - [x] ~Tag new SDK version, if necessary.~ No material changes over beta.
 - [x] Update first-party external dependencies to use new API & SDK
       modules, if necessary.
      - [x] [`go-kms-wrapping`](https://github.com/openbao/go-kms-wrapping) --> https://github.com/openbao/go-kms-wrapping/pull/15
      - [x] ~[`go-secure-stdlib`](https://github.com/openbao/go-secure-stdlib)~ this module isn't used until #17 is completed.
      - [x] [`openbao-template`](https://github.com/openbao/openbao-template) --> https://github.com/openbao/openbao-template/pull/4
 - [x] Update API, SDK, and first-party external dependencies in main
       `go.mod`. While API and SDK always use the built-in version, the
       first-party external modules still use the external version and thus
       must be updated. --> https://github.com/openbao/openbao/pull/770
 - [x] Update external dependencies with vulnerabilities. Major changes should
       be done earlier in the release cycle to give the community time to find
       any breaking issues.
 - [x] Update container image base layer versions.
 - [x] Update Go version pinning in `/.go-release` and in the the `toolchain`
       directive in `go.mod`; go-releaser uses this version via a custom
       (in-repo) `set-up-go` action.

## Release checklist

 - [x] Open PR to update `CHANGELOG.md` and release notes on website. --> https://github.com/openbao/openbao/pull/772 + https://github.com/openbao/openbao/pull/773
 - [x] Tag release commit (`CHANGELOG.md` change).
 - [x] Start [release workflow](https://github.com/openbao/openbao/actions/workflows/release.yml):
       select target tag, and set applicable pre-release/latest set
       (pre-releases should not be marked latest on GitHub). https://github.com/openbao/openbao/actions/runs/12087362599
 - [x] Manually upload [GPG signing key](https://openbao.org/assets/openbao-gpg-pub-20240618.asc)
       to the release artifacts.
 - [x] Spot-check release artifacts:
      - [x] Container images work.
      - [x] Linux binaries work.
      - [x] Website download page.
      - [x] CoSign and GPG Signatures on binaries.
 - [x] In the event of issues during the release that require new tags to be
       pushed, write a postmortem indicating why.
 - [x] Share release notification announcement:
      - [x] OpenBao Core mailing list (cc TSC mailing list)
      - [x] GitHub Discussions
      - [x] Link from Matrix
      - [x] Mention in next community meeting & TSC meetings.
 - [x] Close the release milestone on GitHub.
 - [x] For large releases, work with LF Edge for a release blog post.

**Comment by cipherboy** [comment]
@JanMa @DanGhita I'll work with LF edge after the holidays to get the blog post cross-published to theirs.
